language: node_js
sudo: false
node_js:
  - "0.12"

before_install:

  - export DISPLAY=:99.0

services:
    - xvfb

before_script:
  - export CHROME_BIN=chromium-browser
  - npm install -g grunt-cli

script:
  - grunt travis
